### ISSUE TITLE
3.0+ format XPLT failed to read

### ISSUE THREAD

**Issue by petr-henys** [Nobregaigor/febio-python#1]
Hi,

I use last dev. version of Febio and save to results to xplt 3.0, but reading it gives the following error:

File ~/.local/lib/python3.10/site-packages/febio_python/xplt/xplt_parser/read_xplt.py:77, in read_xplt(xplit_filepath, nstate, verbose)
     [75](file:///home/petr/.local/lib/python3.10/site-packages/febio_python/xplt/xplt_parser/read_xplt.py?line=74) # move cursor to "HDR_VERSION" -> feb file version
     [76](file:///home/petr/.local/lib/python3.10/site-packages/febio_python/xplt/xplt_parser/read_xplt.py?line=75) search_block(bf, TAGS, 'HDR_VERSION', verbose=verbose)
---> [77](file:///home/petr/.local/lib/python3.10/site-packages/febio_python/xplt/xplt_parser/read_xplt.py?line=76) check_fileversion(bf, verbose)
     [79](file:///home/petr/.local/lib/python3.10/site-packages/febio_python/xplt/xplt_parser/read_xplt.py?line=78) # move cursor to "HDR_NODES" -> get number of nodes
     [80](file:///home/petr/.local/lib/python3.10/site-packages/febio_python/xplt/xplt_parser/read_xplt.py?line=79) search_block(bf, TAGS, 'HDR_NODES', verbose=verbose)

File ~/.local/lib/python3.10/site-packages/febio_python/xplt/xplt_parser/read_xplt.py:55, in check_fileversion(bf, verbose)
     [53](file:///home/petr/.local/lib/python3.10/site-packages/febio_python/xplt/xplt_parser/read_xplt.py?line=52)     console_log('Current version is: %d' % version, 2, verbose)
     [54](file:///home/petr/.local/lib/python3.10/site-packages/febio_python/xplt/xplt_parser/read_xplt.py?line=53) else:
---> [55](file:///home/petr/.local/lib/python3.10/site-packages/febio_python/xplt/xplt_parser/read_xplt.py?line=54)     raise(ValueError("Incorrect XPLIT file version: {}".format(version)))

ValueError: Incorrect XPLIT file version: 49

Do I miss something, or is it a bug?

thanks for your great work on parsing febio models!

Petr

**Comment by Nobregaigor** [comment]
Hello @petr-henys , thanks for raising this issue. 

Are you using the latest version on our repository or the latest `pip install` version? We are still under development on the parser for XPLT files with spec 3.0 and the `pip` version might raise this error. If you are using our latest version on GitHub, you should receive a warning about the spec version, but it should still parse it. 

The warning occurs due to a possible error in FEBio Studio. According to their docs, their software should save XPLT files with a spec version tag of "0x0008", but it is saving as "0x00031". I have tried with different samples and the parser identifies "0x00031" as the spec version. Thus, I included both spec versions as acceptable when parsing and, for consistency with their docs, I included a warning for the spec version that does not match their docs. 

However, I updated our `check_fileversion` to raise a clearer error message. 

Please, let me know if you can run the parser with: 

```python
from febio_python import xplt
data = xplt.read_xplt("path/to/file.xplt")
```

**Comment by petr-henys** [comment]
Yes, the issue appeared with pip version. I reinstalled with the last and it raised no issue with file version. However the new error occured with "state":
```
___Begin read header___
___Begin read header___
___Begin read dictionary___
___Begin read mesh___
__node section__
____Begin read states____
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/mnt/data/computing/XPLT_reader/test.py in <cell line: 3>()
      [1](file:///mnt/data/computing/XPLT_reader/test.py?line=0) from febio_python import xplt
----> [3](file:///mnt/data/computing/XPLT_reader/test.py?line=2) model = xplt.read_xplt('jobs/left_femur.xplt', -1, 1)

File ~/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/read_xplt.py:96, in read_xplt(xplit_filepath, nstate, verbose)
     [94](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/read_xplt.py?line=93) elif version == 3.0:
     [95](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/read_xplt.py?line=94)     from .spec_3_0 import read_xplt_3_0
---> [96](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/read_xplt.py?line=95)     return read_xplt_3_0(xplit_filepath, nstate=nstate, verbose=verbose)

File ~/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py:86, in read_xplt_3_0(xplit_filepath, nstate, verbose)
     [79](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py?line=78) # console_log("Nodeset names: {}".format(nodeset_names), 1, verbose)
     [80](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py?line=79) 
     [81](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py?line=80) # -- Explore Parts section --
     [82](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py?line=81) # material = read_materials(bf, TAGS, verbose=verbose)
     [83](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py?line=82) 
     [84](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py?line=83) # -- Read states --
     [85](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py?line=84) console_log("\n____Begin read states____", 1, verbose)
---> [86](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py?line=85) state_data = read_state(bf, TAGS, states_dict, decompress=file_is_compressed, verbose=verbose)
     [88](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py?line=87) console_log('\nData extraction done.', 1, verbose)
     [90](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py?line=89) # close binary file

File ~/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/utils/read_state.py:155, in read_state(bf, TAGS, states_dict, decompress, verbose)
    [153](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/utils/read_state.py?line=152)     nn+=1
...
--> [155](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/utils/read_state.py?line=154)     data_by_name[key] = state_elem_data[ne]
    [156](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/utils/read_state.py?line=155)     ne+=1
    [157](file:///home/petr/.local/lib/python3.10/site-packages/febio_python-0.1.51-py3.10.egg/febio_python/xplt/xplt_parser/spec_3_0/utils/read_state.py?line=156) elif r == 2:

IndexError: index 1 is out of bounds for axis 0 with size 1
```

This error is raised when I run the command:
model = xplt.read_xplt('jobs/left_femur.xplt', -1, 1)

Petr

**Comment by utsekaj42** [comment]
I'm having some issues reading xplt files from CFD ( [sample_cfd.tar.gz](https://github.com/Nobregaigor/febio-python/files/10527987/sample_cfd.tar.gz) ) and FSI analyses. For the attached file I think EOF is reached when reading the first state. There are 10 states in the xplt file. I attach the full output as a file
[full_output.txt](https://github.com/Nobregaigor/febio-python/files/10527989/full_output.txt)

```
import febio_python.xplt as xplt
data = xplt.read_xplt("sample_cfd.xplt", verbose=3)
```

The error traceback is 
```
Traceback (most recent call last):
  File "use_febpython.py", line 2, in <module>
    data = xplt.read_xplt(xplt_path, verbose=3)
  File "src/febio-python/febio_python/xplt/xplt_parser/read_xplt.py", line 96, in read_xplt
    return read_xplt_3_0(xplit_filepath, nstate=nstate, verbose=verbose)
  File "src/febio-python/febio_python/xplt/xplt_parser/spec_3_0/read_xplt_3_0.py", line 86, in read_xplt_3_0
    state_data = read_state(bf, TAGS, states_dict, decompress=file_is_compressed, verbose=verbose)
  File "src/febio-python/febio_python/xplt/xplt_parser/spec_3_0/utils/read_state.py", line 120, in read_state
    n_elems_data = process_state_var(state_elem_data, offset+n_nodes_data)
  File "src/febio-python/febio_python/xplt/xplt_parser/spec_3_0/utils/read_state.py", line 46, in process_state_var
    var_data = read_bytes(bf, nb=data_size, format='f'*(n_data*var_dim))
  File "src/febio-python/febio_python/xplt/xplt_parser/common/utils/read_bytes.py", line 6, in read_bytes
    data = struct.unpack(format, a)
struct.error: unpack requires a buffer of 120 bytes
```

**Comment by Nobregaigor** [comment]
Hello @petr-henys  and @utsekaj42 , I apologize for not addressing your comments earlier. I was focused on other projects and did not have much time. I recently needed to update the `febio-python` package and decided to rework and update the entire package. I just released a new version (`0.2.0`), which includes many significant changes, optimizations and better data structures. I also included conversions to `pyvista` and `vtk`, which allows us to directly visualize either .feb or .xplt files. The documentation can be found here: [https://nobregaigor.github.io/febio-python/](url)

If you are still working with FEBio, please, check the new version of the `febio-python`!

**Comment by Nobregaigor** [comment]
@utsekaj42 I took a look at your file, and I think I found a solution (at least temporary). The error occurs because FEBio is saving `stress` data in the `xplt` state variables section, even though there are no values for this variable during your simulation. When I check your results though FEBio, it shows `stress` as "inactive" for all elements, which I assume it has no value. When reading the binary file, it indeed shows the `stress` data but there is no actual value for it, which results in the `struct.error: unpack requires a buffer of 120 bytes` (it tries to find the data based on the specific data size, but it cannot find). I will try to get in contact with the developers from FEBio to confirm this issue. Maybe they have fixed it already with newer versions (spec 4,0). 

I have applied the required fixes in `read_xplt` and I am now able to read your results:

```python
import pathlib
import pyvista as pv    # For visualization
from febio_python.container import FEBioContainer
from febio_python.utils.pyvista_utils import febio_to_pyvista


samples_dir = pathlib.Path(__file__).parent.parent / "samples"
filepath = samples_dir / "sample_cfd.xplt"

if __name__ == "__main__":
    # read xplt file and load it into a container
    container = FEBioContainer(xplt=filepath)
    # print the xplt object
    print(container.xplt)
    # print(container.xplt)
    last_grid = febio_to_pyvista(container)[-1]
    # extract volumes (hexahedrons in this case):
    last_grid = last_grid.extract_cells_by_type(pv.CellType.HEXAHEDRON)
    # convert to nodal data (for visualization)
    last_grid = last_grid.cell_data_to_point_data()
    # get sample data:
    fluid_stress = last_grid["fluid stress"]
    # plot
    last_grid.plot(scalars=fluid_stress[:, 0], cmap="coolwarm",
                   scalar_bar_args={"title": "Fluid Stress - XX"}, show_edges=True)
```

This will plot the following data:

![image](https://github.com/Nobregaigor/febio-python/assets/42748242/05e37f74-8541-4b84-9054-4dd9077b9982)

Which matched the FEBio results:

![image](https://github.com/Nobregaigor/febio-python/assets/42748242/995840b1-f5e8-4aac-bbd2-05fdc63b67a7)

Please, remember to use the newer version of the `febio-python` package.

**Comment by Nobregaigor** [comment]
@utsekaj42, use version `0.2.1`, version `0.2.0` was uploaded before this last fix.
